# 鏀粯瀹濇敮浠樼浉鍏冲弬鏁?

# 搴旂敤ID,鎮ㄧ殑APPID锛屾敹娆捐处鍙锋棦鏄偍鐨凙PPID瀵瑰簲鏀粯瀹濊处鍙?
alipay.app-id=YOUR_ALIPAY_APP_ID

# 鍟嗘埛PID,鍗栧鏀粯瀹濊处鍙稩D
alipay.seller-id=YOUR_ALIPAY_SELLER_ID

# 鏀粯瀹濈綉鍏?
#alipay.gateway-url=https://openapi.alipaydev.com/gateway.do
alipay.gateway-url=https://openapi-sandbox.dl.alipaydev.com/gateway.do


# 鍟嗘埛绉侀挜锛屾偍鐨凱KCS8鏍煎紡RSA2绉侀挜
alipay.merchant-private-key=YOUR_ALIPAY_MERCHANT_PRIVATE_KEY

# 鏀粯瀹濆叕閽?鏌ョ湅鍦板潃锛歨ttps://openhome.alipay.com/platform/keyManage.htm 瀵瑰簲APPID涓嬬殑鏀粯瀹濆叕閽?
alipay.alipay-public-key=YOUR_ALIPAY_PUBLIC_KEY

# 鎺ュ彛鍐呭鍔犲瘑绉橀挜锛屽绉扮閽?
alipay.content-key=YOUR_ALIPAY_CONTENT_KEY

# 椤甸潰璺宠浆鍚屾閫氱煡椤甸潰璺緞
#alipay.return-url=http://localhost:8080/#/success
alipay.return-url=http://127.0.0.1:8080/#/success

# 鏈嶅姟鍣ㄥ紓姝ラ€氱煡椤甸潰璺緞  闇€http://鏍煎紡鐨勫畬鏁磋矾寰勶紝涓嶈兘鍔?id=123杩欑被鑷畾涔夊弬鏁帮紝蹇呴』澶栫綉鍙互姝ｅ父璁块棶
# 娉ㄦ剰锛氭瘡娆￠噸鏂板惎鍔╪grok锛岄兘闇€瑕佹牴鎹疄闄呮儏鍐典慨鏀硅繖涓厤缃?
#alipay.notify-url= https://f5d9-36-27-0-213.ngrok-free.app/api/ali-pay/trade/notify
#alipay.notify-url= http://340ebc75.r18.cpolar.top/api/ali-pay/trade/notify
#alipay.notify-url= http://735b1376.r10.cpolar.top/api/ali-pay/trade/notify
alipay.notify-url= http://q5j7y2.natappfree.cc/api/ali-pay/trade/notify






