#数据源名称，多数据源以逗号分隔
#spring.shardingsphere.datasource.names=ds-2021,ds-2022,ds-2023,ds-2024,st
spring.shardingsphere.datasource.names=ds-2022,ds-2023,ds-2024,st
# 配置2021数据源
#spring.shardingsphere.datasource.ds-2021.type=com.alibaba.druid.pool.DruidDataSource
#spring.shardingsphere.datasource.ds-2021.driver-class-name=com.mysql.jdbc.Driver
#spring.shardingsphere.datasource.ds-2021.url=jdbc:mysql://127.0.0.1:3306/stock_db_2021?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
#spring.shardingsphere.datasource.ds-2021.username=root
#spring.shardingsphere.datasource.ds-2021.password=YOUR_DB_PASSWORD
# 配置2022数据源
spring.shardingsphere.datasource.ds-2022.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.ds-2022.driver-class-name=com.mysql.jdbc.Driver
spring.shardingsphere.datasource.ds-2022.url=jdbc:mysql://127.0.0.1:3306/stock_db_2022?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
spring.shardingsphere.datasource.ds-2022.username=YOUR_DB_USER
spring.shardingsphere.datasource.ds-2022.password=YOUR_DB_PASSWORD
# 配置2023数据源
spring.shardingsphere.datasource.ds-2023.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.ds-2023.driver-class-name=com.mysql.jdbc.Driver
spring.shardingsphere.datasource.ds-2023.url=jdbc:mysql://127.0.0.1:3306/stock_db_2023?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
spring.shardingsphere.datasource.ds-2023.username=YOUR_DB_USER
spring.shardingsphere.datasource.ds-2023.password=YOUR_DB_PASSWORD
# 配置2024数据源
spring.shardingsphere.datasource.ds-2024.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.ds-2024.driver-class-name=com.mysql.jdbc.Driver
spring.shardingsphere.datasource.ds-2024.url=jdbc:mysql://127.0.0.1:3306/stock_db_2024?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
spring.shardingsphere.datasource.ds-2024.username=YOUR_DB_USER
spring.shardingsphere.datasource.ds-2024.password=YOUR_DB_PASSWORD
# 配置默认数据源
spring.shardingsphere.datasource.st.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.st.driver-class-name=com.mysql.jdbc.Driver
spring.shardingsphere.datasource.st.url=jdbc:mysql://127.0.0.1:3306/stock_sys_db?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
spring.shardingsphere.datasource.st.username=YOUR_DB_USER
spring.shardingsphere.datasource.st.password=YOUR_DB_PASSWORD

#公共 广播表
spring.shardingsphere.sharding.broadcast-tables=stock_business,stock_market_log_price
# 由数据源名 + 表名组成，以小数点分隔。多个表以逗号分隔，支持 inline 表达式。缺省表示使用已知数据源与逻辑表名称生成数据节点，用于广播表（即每个库中都需要一个同样的表用于关联查询，多为字典表）
# 或只分库不分表且所有库的表结构完全一致的情况
#配置股票流水的数据节点
#spring.shardingsphere.sharding.tables.stock_rt_info.actual-data-nodes=ds-2021.stock_rt_info_$->{202101..202112},ds-2022.stock_rt_info_$->{202201..202212},ds-2023.stock_rt_info_$->{202301..202312},ds-2024.stock_rt_info_$->{202401..202412}
spring.shardingsphere.sharding.tables.stock_rt_info.actual-data-nodes=ds-2022.stock_rt_info_$->{202201..202212},ds-2023.stock_rt_info_$->{202301..202312},ds-2024.stock_rt_info_$->{202401..202412}

#股票流水表
# 用于单分片键的标准分片场景，库分片规则
spring.shardingsphere.sharding.tables.stock_rt_info.database-strategy.standard.sharding-column=cur_time
spring.shardingsphere.sharding.tables.stock_rt_info.database-strategy.standard.precise-algorithm-class-name=com.ys.stock.sharding.CommonDbPreciseShardingAlgorithm
spring.shardingsphere.sharding.tables.stock_rt_info.database-strategy.standard.range-algorithm-class-name=com.ys.stock.sharding.CommonDbRangeShardingAlgorithm
# 用于单分片键的标准分片场景,表分片规则
spring.shardingsphere.sharding.tables.stock_rt_info.table-strategy.standard.sharding-column=cur_time
spring.shardingsphere.sharding.tables.stock_rt_info.table-strategy.standard.precise-algorithm-class-name=com.ys.stock.sharding.StockRtInfoTablePreciseHandler
spring.shardingsphere.sharding.tables.stock_rt_info.table-strategy.standard.range-algorithm-class-name=com.ys.stock.sharding.StockRtInfoTableRangeHandler

#配置板块流水的数据节点
#spring.shardingsphere.sharding.tables.stock_block_rt_info.actual-data-nodes=ds-$->{2021..2024}.stock_block_rt_info
spring.shardingsphere.sharding.tables.stock_block_rt_info.actual-data-nodes=ds-$->{2022..2024}.stock_block_rt_info
#股票板块流水表
# 用于单分片键的标准分片场景，库分片规则
spring.shardingsphere.sharding.tables.stock_block_rt_info.database-strategy.standard.sharding-column=cur_time
spring.shardingsphere.sharding.tables.stock_block_rt_info.database-strategy.standard.precise-algorithm-class-name=com.ys.stock.sharding.CommonDbPreciseShardingAlgorithm
spring.shardingsphere.sharding.tables.stock_block_rt_info.database-strategy.standard.range-algorithm-class-name=com.ys.stock.sharding.CommonDbRangeShardingAlgorithm
# 用于单分片键的标准分片场景,表分片规则
spring.shardingsphere.sharding.tables.stock_block_rt_info.table-strategy.standard.sharding-column=cur_time
spring.shardingsphere.sharding.tables.stock_block_rt_info.table-strategy.standard.precise-algorithm-class-name=com.ys.stock.sharding.CommonTbPreciseShardingAlgorithm
spring.shardingsphere.sharding.tables.stock_block_rt_info.table-strategy.standard.range-algorithm-class-name=com.ys.stock.sharding.CommonTbRangeShardingAlgorithm

#配置大盘流水的数据节点
#spring.shardingsphere.sharding.tables.stock_market_index_info.actual-data-nodes=ds-$->{2021..2024}.stock_market_index_info
spring.shardingsphere.sharding.tables.stock_market_index_info.actual-data-nodes=ds-$->{2022..2024}.stock_market_index_info
#股票大盘流水表
# 用于单分片键的标准分片场景，库分片规则
spring.shardingsphere.sharding.tables.stock_market_index_info.database-strategy.standard.sharding-column=cur_time
spring.shardingsphere.sharding.tables.stock_market_index_info.database-strategy.standard.precise-algorithm-class-name=com.ys.stock.sharding.CommonDbPreciseShardingAlgorithm
spring.shardingsphere.sharding.tables.stock_market_index_info.database-strategy.standard.range-algorithm-class-name=com.ys.stock.sharding.CommonDbRangeShardingAlgorithm
# 用于单分片键的标准分片场景,表分片规则
spring.shardingsphere.sharding.tables.stock_market_index_info.table-strategy.standard.sharding-column=cur_time
spring.shardingsphere.sharding.tables.stock_market_index_info.table-strategy.standard.precise-algorithm-class-name=com.ys.stock.sharding.CommonTbPreciseShardingAlgorithm
spring.shardingsphere.sharding.tables.stock_market_index_info.table-strategy.standard.range-algorithm-class-name=com.ys.stock.sharding.CommonTbRangeShardingAlgorithm

# 主键生成策略
#spring.shardingsphere.sharding.tables.stock-rt_info.key-generator.column=id
#spring.shardingsphere.sharding.tables.stock-rt_info.key-generator.type=SNOWFLAKE
# 配置默认数据源(未配置分片规则的表将通过默认数据源定位)
spring.shardingsphere.sharding.default-data-source-name=st
# 是否开启 SQL 显示，默认值: false
spring.shardingsphere.props.sql.show=false
# 工作线程数量，默认值: CPU 核数
spring.shardingsphere.props.executor.size=8
